spring:
  application:
    name: user
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:user;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
#      ddl-auto: update
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    url: jdbc:h2:mem:user;DB_CLOSE_DELAY=-1
    baseline-on-migrate: true
    user: sa
    password:

